import { sqliteTable, text, integer, real, uniqueIndex, index } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";

export const companies = sqliteTable("companies", {
  userId: text("user_id").primaryKey(),
  email: text("email").notNull(),
  name: text("name").notNull(),
  address: text("address").notNull(),
  city: text("city").notNull(),
  postalCode: text("postal_code").notNull().default(""),
  jib: text("jib").notNull(),
  vatId: text("vat_id").notNull().default(""),
  vatRegistered: integer("vat_registered", { mode: "boolean" }).notNull().default(false),
  iban: text("iban").notNull().default(""),
  bank: text("bank").notNull().default(""),
  phone: text("phone").notNull().default(""),
  contactEmail: text("contact_email").notNull().default(""),
  contactPerson: text("contact_person").notNull().default(""),
  defaultNote: text("default_note").notNull().default(""),
  responsiblePerson: text("responsible_person").notNull().default(""),
  electronicNotice: integer("electronic_notice", { mode: "boolean" }).notNull().default(true),
  showSignatureLine: integer("show_signature_line", { mode: "boolean" }).notNull().default(false),
  logoKey: text("logo_key"),
  status: text("status").notNull().default("approved"),
  plan: text("plan").notNull().default("free"),
  priceBam: real("price_bam").notNull().default(22),
  paidUntil: text("paid_until"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (t) => [index("idx_companies_status").on(t.status)]);

export const documents = sqliteTable("documents", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  type: text("type").notNull(),
  title: text("title").notNull(),
  number: text("number").notNull(),
  issueDate: text("issue_date").notNull(),
  dueDate: text("due_date").notNull().default(""),
  clientName: text("client_name").notNull(),
  clientAddress: text("client_address").notNull().default(""),
  clientId: text("client_id").notNull().default(""),
  clientContact: text("client_contact").notNull().default(""),
  showClientContact: integer("show_client_contact", { mode: "boolean" }).notNull().default(false),
  showIssuerContact: integer("show_issuer_contact", { mode: "boolean" }).notNull().default(false),
  fiscalNumber: text("fiscal_number").notNull().default(""),
  currency: text("currency").notNull().default("KM"),
  itemsJson: text("items_json").notNull(),
  issuerJson: text("issuer_json").notNull(),
  notes: text("notes").notNull().default(""),
  month: text("month").notNull(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (t) => [
  uniqueIndex("idx_documents_owner_number").on(t.userId, t.number),
  index("idx_documents_owner_date").on(t.userId, t.createdAt),
  index("idx_documents_owner_month").on(t.userId, t.month),
]);

export const customers = sqliteTable("customers", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  name: text("name").notNull(),
  address: text("address").notNull().default(""),
  city: text("city").notNull().default(""),
  postalCode: text("postal_code").notNull().default(""),
  jib: text("jib").notNull().default(""),
  vatId: text("vat_id").notNull().default(""),
  email: text("email").notNull().default(""),
  phone: text("phone").notNull().default(""),
  contactPerson: text("contact_person").notNull().default(""),
  contactEmail: text("contact_email").notNull().default(""),
  contactPhone: text("contact_phone").notNull().default(""),
  notes: text("notes").notNull().default(""),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (t) => [index("idx_customers_user_name").on(t.userId, t.name)]);

export const catalogItems = sqliteTable("catalog_items", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  kind: text("kind").notNull().default("service"),
  name: text("name").notNull(),
  description: text("description").notNull().default(""),
  sku: text("sku").notNull().default(""),
  unit: text("unit").notNull().default("kom"),
  price: real("price").notNull().default(0),
  vat: real("vat").notNull().default(17),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (t) => [index("idx_catalog_user_name").on(t.userId, t.name)]);

export const billingSettings = sqliteTable("billing_settings", {
  id: integer("id").primaryKey(),
  name: text("name").notNull().default("BRATTS d.o.o."),
  address: text("address").notNull().default(""),
  city: text("city").notNull().default(""),
  postalCode: text("postal_code").notNull().default(""),
  jib: text("jib").notNull().default(""),
  vatId: text("vat_id").notNull().default(""),
  iban: text("iban").notNull().default(""),
  bank: text("bank").notNull().default(""),
  email: text("email").notNull().default("electroace@gmail.com"),
  updatedAt: text("updated_at").notNull(),
});

export const planRequests = sqliteTable("plan_requests", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  number: text("number").notNull().unique(),
  amountCents: integer("amount_cents").notNull(),
  baseCents: integer("base_cents").notNull(),
  vatCents: integer("vat_cents").notNull(),
  issuerJson: text("issuer_json").notNull(),
  customerJson: text("customer_json").notNull(),
  status: text("status").notNull().default("pending"),
  emailStatus: text("email_status").notNull().default("not_configured"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (t) => [
  index("idx_plan_requests_user").on(t.userId, t.createdAt),
  uniqueIndex("idx_plan_requests_one_pending").on(t.userId).where(sql`${t.status} = 'pending'`),
]);
